
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("7b902349-318e-4e6f-acb3-49f253ab3167")>
#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class School
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new School object using the connection string found in the 'School' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=School", "School")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new School object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "School")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new School object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "School")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Courses() As ObjectSet(Of Course)
        Get
            If (_Courses Is Nothing) Then
                _Courses = MyBase.CreateObjectSet(Of Course)("Courses")
            End If
            Return _Courses
        End Get
    End Property

    Private _Courses As ObjectSet(Of Course)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Courses EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCourses(ByVal course As Course)
        MyBase.AddObject("Courses", course)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SchoolModel", Name:="Course")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Course
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Course object.
    ''' </summary>
    ''' <param name="courseID">Initial value of the CourseID property.</param>
    ''' <param name="title">Initial value of the Title property.</param>
    ''' <param name="credits">Initial value of the Credits property.</param>
    ''' <param name="departmentID">Initial value of the DepartmentID property.</param>
    Public Shared Function CreateCourse(courseID As Global.System.String, title As Global.System.String, credits As Global.System.Int32, departmentID As Global.System.Int32) As Course
        Dim course as Course = New Course
        course.CourseID = courseID
        course.Title = title
        course.Credits = credits
        course.DepartmentID = departmentID
        Return course
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property CourseID() As Global.System.String
        Get
            Return _CourseID
        End Get
        Set
            If (_CourseID <> Value) Then
                OnCourseIDChanging(value)
                ReportPropertyChanging("CourseID")
                _CourseID = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("CourseID")
                OnCourseIDChanged()
            End If
        End Set
    End Property

    Private _CourseID As Global.System.String
    Private Partial Sub OnCourseIDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCourseIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Title() As Global.System.String
        Get
            Return _Title
        End Get
        Set
            OnTitleChanging(value)
            ReportPropertyChanging("Title")
            _Title = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Title")
            OnTitleChanged()
        End Set
    End Property

    Private _Title As Global.System.String
    Private Partial Sub OnTitleChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTitleChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Credits() As Global.System.Int32
        Get
            Return _Credits
        End Get
        Set
            OnCreditsChanging(value)
            ReportPropertyChanging("Credits")
            _Credits = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Credits")
            OnCreditsChanged()
        End Set
    End Property

    Private _Credits As Global.System.Int32
    Private Partial Sub OnCreditsChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnCreditsChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DepartmentID() As Global.System.Int32
        Get
            Return _DepartmentID
        End Get
        Set
            OnDepartmentIDChanging(value)
            ReportPropertyChanging("DepartmentID")
            _DepartmentID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DepartmentID")
            OnDepartmentIDChanged()
        End Set
    End Property

    Private _DepartmentID As Global.System.Int32
    Private Partial Sub OnDepartmentIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnDepartmentIDChanged()
    End Sub

    #End Region

End Class

#End Region


