//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSOutlookCallWCFInteractWithWF.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Leave", Namespace="http://schemas.datacontract.org/2004/07/DBOperate")]
    [System.SerializableAttribute()]
    public partial class Leave : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LeaveDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid LeaveIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeaveNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LeaveDay {
            get {
                return this.LeaveDayField;
            }
            set {
                if ((this.LeaveDayField.Equals(value) != true)) {
                    this.LeaveDayField = value;
                    this.RaisePropertyChanged("LeaveDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid LeaveID {
            get {
                return this.LeaveIDField;
            }
            set {
                if ((this.LeaveIDField.Equals(value) != true)) {
                    this.LeaveIDField = value;
                    this.RaisePropertyChanged("LeaveID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeaveName {
            get {
                return this.LeaveNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LeaveNameField, value) != true)) {
                    this.LeaveNameField = value;
                    this.RaisePropertyChanged("LeaveName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ILeaveService")]
    public interface ILeaveService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeaveService/GetLeaveList", ReplyAction="http://tempuri.org/ILeaveService/GetLeaveListResponse")]
        CSOutlookCallWCFInteractWithWF.ServiceReference1.Leave[] GetLeaveList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeaveService/CreateLeave", ReplyAction="http://tempuri.org/ILeaveService/CreateLeaveResponse")]
        void CreateLeave(string name, string day);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeaveService/AuditingLeave", ReplyAction="http://tempuri.org/ILeaveService/AuditingLeaveResponse")]
        void AuditingLeave(string id, string comment);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILeaveServiceChannel : CSOutlookCallWCFInteractWithWF.ServiceReference1.ILeaveService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LeaveServiceClient : System.ServiceModel.ClientBase<CSOutlookCallWCFInteractWithWF.ServiceReference1.ILeaveService>, CSOutlookCallWCFInteractWithWF.ServiceReference1.ILeaveService {
        
        public LeaveServiceClient() {
        }
        
        public LeaveServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LeaveServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeaveServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeaveServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CSOutlookCallWCFInteractWithWF.ServiceReference1.Leave[] GetLeaveList() {
            return base.Channel.GetLeaveList();
        }
        
        public void CreateLeave(string name, string day) {
            base.Channel.CreateLeave(name, day);
        }
        
        public void AuditingLeave(string id, string comment) {
            base.Channel.AuditingLeave(id, comment);
        }
    }
}
