'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18051
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace TranslatorService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TranslateOptions", [Namespace]:="http://schemas.datacontract.org/2004/07/Microsoft.MT.Web.Service.V2"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TranslateOptions
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CategoryField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ContentTypeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IncludeMultipleMTAlternativesField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReservedFlagsField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UriField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Category() As String
            Get
                Return Me.CategoryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CategoryField, value) <> true) Then
                    Me.CategoryField = value
                    Me.RaisePropertyChanged("Category")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ContentType() As String
            Get
                Return Me.ContentTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ContentTypeField, value) <> true) Then
                    Me.ContentTypeField = value
                    Me.RaisePropertyChanged("ContentType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property IncludeMultipleMTAlternatives() As Boolean
            Get
                Return Me.IncludeMultipleMTAlternativesField
            End Get
            Set
                If (Me.IncludeMultipleMTAlternativesField.Equals(value) <> true) Then
                    Me.IncludeMultipleMTAlternativesField = value
                    Me.RaisePropertyChanged("IncludeMultipleMTAlternatives")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ReservedFlags() As String
            Get
                Return Me.ReservedFlagsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReservedFlagsField, value) <> true) Then
                    Me.ReservedFlagsField = value
                    Me.RaisePropertyChanged("ReservedFlags")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property State() As String
            Get
                Return Me.StateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StateField, value) <> true) Then
                    Me.StateField = value
                    Me.RaisePropertyChanged("State")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Uri() As String
            Get
                Return Me.UriField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UriField, value) <> true) Then
                    Me.UriField = value
                    Me.RaisePropertyChanged("Uri")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property User() As String
            Get
                Return Me.UserField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserField, value) <> true) Then
                    Me.UserField = value
                    Me.RaisePropertyChanged("User")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GetTranslationsResponse", [Namespace]:="http://schemas.datacontract.org/2004/07/Microsoft.MT.Web.Service.V2"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GetTranslationsResponse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FromField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TranslationsField() As TranslatorService.TranslationMatch
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property From() As String
            Get
                Return Me.FromField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FromField, value) <> true) Then
                    Me.FromField = value
                    Me.RaisePropertyChanged("From")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property State() As String
            Get
                Return Me.StateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StateField, value) <> true) Then
                    Me.StateField = value
                    Me.RaisePropertyChanged("State")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Translations() As TranslatorService.TranslationMatch()
            Get
                Return Me.TranslationsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TranslationsField, value) <> true) Then
                    Me.TranslationsField = value
                    Me.RaisePropertyChanged("Translations")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TranslationMatch", [Namespace]:="http://schemas.datacontract.org/2004/07/Microsoft.MT.Web.Service.V2"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TranslationMatch
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private CountField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorField As String
        
        Private MatchDegreeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MatchedOriginalTextField As String
        
        Private RatingField As Integer
        
        Private TranslatedTextField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Count() As Integer
            Get
                Return Me.CountField
            End Get
            Set
                If (Me.CountField.Equals(value) <> true) Then
                    Me.CountField = value
                    Me.RaisePropertyChanged("Count")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property [Error]() As String
            Get
                Return Me.ErrorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErrorField, value) <> true) Then
                    Me.ErrorField = value
                    Me.RaisePropertyChanged("Error")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property MatchDegree() As Integer
            Get
                Return Me.MatchDegreeField
            End Get
            Set
                If (Me.MatchDegreeField.Equals(value) <> true) Then
                    Me.MatchDegreeField = value
                    Me.RaisePropertyChanged("MatchDegree")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property MatchedOriginalText() As String
            Get
                Return Me.MatchedOriginalTextField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MatchedOriginalTextField, value) <> true) Then
                    Me.MatchedOriginalTextField = value
                    Me.RaisePropertyChanged("MatchedOriginalText")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Rating() As Integer
            Get
                Return Me.RatingField
            End Get
            Set
                If (Me.RatingField.Equals(value) <> true) Then
                    Me.RatingField = value
                    Me.RaisePropertyChanged("Rating")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property TranslatedText() As String
            Get
                Return Me.TranslatedTextField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TranslatedTextField, value) <> true) Then
                    Me.TranslatedTextField = value
                    Me.RaisePropertyChanged("TranslatedText")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Translation", [Namespace]:="http://schemas.datacontract.org/2004/07/Microsoft.MT.Web.Service.V2"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Translation
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private OriginalTextField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RatingField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SequenceField As Integer
        
        Private TranslatedTextField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property OriginalText() As String
            Get
                Return Me.OriginalTextField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OriginalTextField, value) <> true) Then
                    Me.OriginalTextField = value
                    Me.RaisePropertyChanged("OriginalText")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Rating() As Integer
            Get
                Return Me.RatingField
            End Get
            Set
                If (Me.RatingField.Equals(value) <> true) Then
                    Me.RatingField = value
                    Me.RaisePropertyChanged("Rating")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Sequence() As Integer
            Get
                Return Me.SequenceField
            End Get
            Set
                If (Me.SequenceField.Equals(value) <> true) Then
                    Me.SequenceField = value
                    Me.RaisePropertyChanged("Sequence")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property TranslatedText() As String
            Get
                Return Me.TranslatedTextField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TranslatedTextField, value) <> true) Then
                    Me.TranslatedTextField = value
                    Me.RaisePropertyChanged("TranslatedText")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TranslateArrayResponse", [Namespace]:="http://schemas.datacontract.org/2004/07/Microsoft.MT.Web.Service.V2"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TranslateArrayResponse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FromField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OriginalTextSentenceLengthsField() As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TranslatedTextField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TranslatedTextSentenceLengthsField() As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property [Error]() As String
            Get
                Return Me.ErrorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErrorField, value) <> true) Then
                    Me.ErrorField = value
                    Me.RaisePropertyChanged("Error")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property From() As String
            Get
                Return Me.FromField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FromField, value) <> true) Then
                    Me.FromField = value
                    Me.RaisePropertyChanged("From")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property OriginalTextSentenceLengths() As Integer()
            Get
                Return Me.OriginalTextSentenceLengthsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OriginalTextSentenceLengthsField, value) <> true) Then
                    Me.OriginalTextSentenceLengthsField = value
                    Me.RaisePropertyChanged("OriginalTextSentenceLengths")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property State() As String
            Get
                Return Me.StateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StateField, value) <> true) Then
                    Me.StateField = value
                    Me.RaisePropertyChanged("State")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property TranslatedText() As String
            Get
                Return Me.TranslatedTextField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TranslatedTextField, value) <> true) Then
                    Me.TranslatedTextField = value
                    Me.RaisePropertyChanged("TranslatedText")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property TranslatedTextSentenceLengths() As Integer()
            Get
                Return Me.TranslatedTextSentenceLengthsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TranslatedTextSentenceLengthsField, value) <> true) Then
                    Me.TranslatedTextSentenceLengthsField = value
                    Me.RaisePropertyChanged("TranslatedTextSentenceLengths")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TranslateArray2Response", [Namespace]:="http://schemas.datacontract.org/2004/07/Microsoft.MT.Web.Service.V2"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TranslateArray2Response
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AlignmentField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FromField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OriginalTextSentenceLengthsField() As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TranslatedTextField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TranslatedTextSentenceLengthsField() As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Alignment() As String
            Get
                Return Me.AlignmentField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AlignmentField, value) <> true) Then
                    Me.AlignmentField = value
                    Me.RaisePropertyChanged("Alignment")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property [Error]() As String
            Get
                Return Me.ErrorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErrorField, value) <> true) Then
                    Me.ErrorField = value
                    Me.RaisePropertyChanged("Error")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property From() As String
            Get
                Return Me.FromField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FromField, value) <> true) Then
                    Me.FromField = value
                    Me.RaisePropertyChanged("From")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property OriginalTextSentenceLengths() As Integer()
            Get
                Return Me.OriginalTextSentenceLengthsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OriginalTextSentenceLengthsField, value) <> true) Then
                    Me.OriginalTextSentenceLengthsField = value
                    Me.RaisePropertyChanged("OriginalTextSentenceLengths")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property State() As String
            Get
                Return Me.StateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StateField, value) <> true) Then
                    Me.StateField = value
                    Me.RaisePropertyChanged("State")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property TranslatedText() As String
            Get
                Return Me.TranslatedTextField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TranslatedTextField, value) <> true) Then
                    Me.TranslatedTextField = value
                    Me.RaisePropertyChanged("TranslatedText")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property TranslatedTextSentenceLengths() As Integer()
            Get
                Return Me.TranslatedTextSentenceLengthsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TranslatedTextSentenceLengthsField, value) <> true) Then
                    Me.TranslatedTextSentenceLengthsField = value
                    Me.RaisePropertyChanged("TranslatedTextSentenceLengths")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://api.microsofttranslator.com/V2", ConfigurationName:="TranslatorService.LanguageService")>  _
    Public Interface LanguageService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.microsofttranslator.com/V2/LanguageService/AddTranslation", ReplyAction:="http://api.microsofttranslator.com/V2/LanguageService/AddTranslationResponse")>  _
        Sub AddTranslation(ByVal appId As String, ByVal originalText As String, ByVal translatedText As String, ByVal from As String, ByVal [to] As String, ByVal rating As Integer, ByVal contentType As String, ByVal category As String, ByVal user As String, ByVal uri As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.microsofttranslator.com/V2/LanguageService/BreakSentences", ReplyAction:="http://api.microsofttranslator.com/V2/LanguageService/BreakSentencesResponse")>  _
        Function BreakSentences(ByVal appId As String, ByVal text As String, ByVal language As String) As Integer()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.microsofttranslator.com/V2/LanguageService/Detect", ReplyAction:="http://api.microsofttranslator.com/V2/LanguageService/DetectResponse")>  _
        Function Detect(ByVal appId As String, ByVal text As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.microsofttranslator.com/V2/LanguageService/DetectArray", ReplyAction:="http://api.microsofttranslator.com/V2/LanguageService/DetectArrayResponse")>  _
        Function DetectArray(ByVal appId As String, ByVal texts() As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.microsofttranslator.com/V2/LanguageService/GetAppIdToken", ReplyAction:="http://api.microsofttranslator.com/V2/LanguageService/GetAppIdTokenResponse")>  _
        Function GetAppIdToken(ByVal appId As String, ByVal minRatingRead As Integer, ByVal maxRatingWrite As Integer, ByVal expireSeconds As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.microsofttranslator.com/V2/LanguageService/GetLanguageNames", ReplyAction:="http://api.microsofttranslator.com/V2/LanguageService/GetLanguageNamesResponse")>  _
        Function GetLanguageNames(ByVal appId As String, ByVal locale As String, ByVal languageCodes() As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.microsofttranslator.com/V2/LanguageService/GetLanguagesForSpeak", ReplyAction:="http://api.microsofttranslator.com/V2/LanguageService/GetLanguagesForSpeakRespons"& _ 
            "e")>  _
        Function GetLanguagesForSpeak(ByVal appId As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.microsofttranslator.com/V2/LanguageService/GetLanguagesForTranslate", ReplyAction:="http://api.microsofttranslator.com/V2/LanguageService/GetLanguagesForTranslateRes"& _ 
            "ponse")>  _
        Function GetLanguagesForTranslate(ByVal appId As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.microsofttranslator.com/V2/LanguageService/GetTranslations", ReplyAction:="http://api.microsofttranslator.com/V2/LanguageService/GetTranslationsResponse")>  _
        Function GetTranslations(ByVal appId As String, ByVal text As String, ByVal from As String, ByVal [to] As String, ByVal maxTranslations As Integer, ByVal options As TranslatorService.TranslateOptions) As TranslatorService.GetTranslationsResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.microsofttranslator.com/V2/LanguageService/Translate", ReplyAction:="http://api.microsofttranslator.com/V2/LanguageService/TranslateResponse")>  _
        Function Translate(ByVal appId As String, ByVal text As String, ByVal from As String, ByVal [to] As String, ByVal contentType As String, ByVal category As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.microsofttranslator.com/V2/LanguageService/AddTranslationArray", ReplyAction:="http://api.microsofttranslator.com/V2/LanguageService/AddTranslationArrayResponse"& _ 
            "")>  _
        Sub AddTranslationArray(ByVal appId As String, ByVal translations() As TranslatorService.Translation, ByVal from As String, ByVal [to] As String, ByVal options As TranslatorService.TranslateOptions)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.microsofttranslator.com/V2/LanguageService/GetTranslationsArray", ReplyAction:="http://api.microsofttranslator.com/V2/LanguageService/GetTranslationsArrayRespons"& _ 
            "e")>  _
        Function GetTranslationsArray(ByVal appId As String, ByVal texts() As String, ByVal from As String, ByVal [to] As String, ByVal maxTranslations As Integer, ByVal options As TranslatorService.TranslateOptions) As TranslatorService.GetTranslationsResponse()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.microsofttranslator.com/V2/LanguageService/Speak", ReplyAction:="http://api.microsofttranslator.com/V2/LanguageService/SpeakResponse")>  _
        Function Speak(ByVal appId As String, ByVal text As String, ByVal language As String, ByVal format As String, ByVal options As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.microsofttranslator.com/V2/LanguageService/TranslateArray", ReplyAction:="http://api.microsofttranslator.com/V2/LanguageService/TranslateArrayResponse")>  _
        Function TranslateArray(ByVal appId As String, ByVal texts() As String, ByVal from As String, ByVal [to] As String, ByVal options As TranslatorService.TranslateOptions) As TranslatorService.TranslateArrayResponse()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.microsofttranslator.com/V2/LanguageService/TranslateArray2", ReplyAction:="http://api.microsofttranslator.com/V2/LanguageService/TranslateArray2Response")>  _
        Function TranslateArray2(ByVal appId As String, ByVal texts() As String, ByVal from As String, ByVal [to] As String, ByVal options As TranslatorService.TranslateOptions) As TranslatorService.TranslateArray2Response()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface LanguageServiceChannel
        Inherits TranslatorService.LanguageService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class LanguageServiceClient
        Inherits System.ServiceModel.ClientBase(Of TranslatorService.LanguageService)
        Implements TranslatorService.LanguageService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub AddTranslation(ByVal appId As String, ByVal originalText As String, ByVal translatedText As String, ByVal from As String, ByVal [to] As String, ByVal rating As Integer, ByVal contentType As String, ByVal category As String, ByVal user As String, ByVal uri As String) Implements TranslatorService.LanguageService.AddTranslation
            MyBase.Channel.AddTranslation(appId, originalText, translatedText, from, [to], rating, contentType, category, user, uri)
        End Sub
        
        Public Function BreakSentences(ByVal appId As String, ByVal text As String, ByVal language As String) As Integer() Implements TranslatorService.LanguageService.BreakSentences
            Return MyBase.Channel.BreakSentences(appId, text, language)
        End Function
        
        Public Function Detect(ByVal appId As String, ByVal text As String) As String Implements TranslatorService.LanguageService.Detect
            Return MyBase.Channel.Detect(appId, text)
        End Function
        
        Public Function DetectArray(ByVal appId As String, ByVal texts() As String) As String() Implements TranslatorService.LanguageService.DetectArray
            Return MyBase.Channel.DetectArray(appId, texts)
        End Function
        
        Public Function GetAppIdToken(ByVal appId As String, ByVal minRatingRead As Integer, ByVal maxRatingWrite As Integer, ByVal expireSeconds As Integer) As String Implements TranslatorService.LanguageService.GetAppIdToken
            Return MyBase.Channel.GetAppIdToken(appId, minRatingRead, maxRatingWrite, expireSeconds)
        End Function
        
        Public Function GetLanguageNames(ByVal appId As String, ByVal locale As String, ByVal languageCodes() As String) As String() Implements TranslatorService.LanguageService.GetLanguageNames
            Return MyBase.Channel.GetLanguageNames(appId, locale, languageCodes)
        End Function
        
        Public Function GetLanguagesForSpeak(ByVal appId As String) As String() Implements TranslatorService.LanguageService.GetLanguagesForSpeak
            Return MyBase.Channel.GetLanguagesForSpeak(appId)
        End Function
        
        Public Function GetLanguagesForTranslate(ByVal appId As String) As String() Implements TranslatorService.LanguageService.GetLanguagesForTranslate
            Return MyBase.Channel.GetLanguagesForTranslate(appId)
        End Function
        
        Public Function GetTranslations(ByVal appId As String, ByVal text As String, ByVal from As String, ByVal [to] As String, ByVal maxTranslations As Integer, ByVal options As TranslatorService.TranslateOptions) As TranslatorService.GetTranslationsResponse Implements TranslatorService.LanguageService.GetTranslations
            Return MyBase.Channel.GetTranslations(appId, text, from, [to], maxTranslations, options)
        End Function
        
        Public Function Translate(ByVal appId As String, ByVal text As String, ByVal from As String, ByVal [to] As String, ByVal contentType As String, ByVal category As String) As String Implements TranslatorService.LanguageService.Translate
            Return MyBase.Channel.Translate(appId, text, from, [to], contentType, category)
        End Function
        
        Public Sub AddTranslationArray(ByVal appId As String, ByVal translations() As TranslatorService.Translation, ByVal from As String, ByVal [to] As String, ByVal options As TranslatorService.TranslateOptions) Implements TranslatorService.LanguageService.AddTranslationArray
            MyBase.Channel.AddTranslationArray(appId, translations, from, [to], options)
        End Sub
        
        Public Function GetTranslationsArray(ByVal appId As String, ByVal texts() As String, ByVal from As String, ByVal [to] As String, ByVal maxTranslations As Integer, ByVal options As TranslatorService.TranslateOptions) As TranslatorService.GetTranslationsResponse() Implements TranslatorService.LanguageService.GetTranslationsArray
            Return MyBase.Channel.GetTranslationsArray(appId, texts, from, [to], maxTranslations, options)
        End Function
        
        Public Function Speak(ByVal appId As String, ByVal text As String, ByVal language As String, ByVal format As String, ByVal options As String) As String Implements TranslatorService.LanguageService.Speak
            Return MyBase.Channel.Speak(appId, text, language, format, options)
        End Function
        
        Public Function TranslateArray(ByVal appId As String, ByVal texts() As String, ByVal from As String, ByVal [to] As String, ByVal options As TranslatorService.TranslateOptions) As TranslatorService.TranslateArrayResponse() Implements TranslatorService.LanguageService.TranslateArray
            Return MyBase.Channel.TranslateArray(appId, texts, from, [to], options)
        End Function
        
        Public Function TranslateArray2(ByVal appId As String, ByVal texts() As String, ByVal from As String, ByVal [to] As String, ByVal options As TranslatorService.TranslateOptions) As TranslatorService.TranslateArray2Response() Implements TranslatorService.LanguageService.TranslateArray2
            Return MyBase.Channel.TranslateArray2(appId, texts, from, [to], options)
        End Function
    End Class
End Namespace
