

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class StackPanel;
                ref class TextBlock;
                ref class TextBox;
                ref class Button;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            ref class VisualState;
        }
    }
}

namespace CppWindowsStoreAppHttpClientPostJson
{
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ ContentRoot;
        private: ::Windows::UI::Xaml::Controls::Grid^ TitleGrid;
        private: ::Windows::UI::Xaml::Controls::Grid^ Footer;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ FooterPanel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ StatusBlock;
        private: ::Windows::UI::Xaml::Controls::Grid^ Input;
        private: ::Windows::UI::Xaml::Controls::Grid^ Output;
        private: ::Windows::UI::Xaml::Controls::TextBox^ OutputField;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ NamePanel;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ AgePanel;
        private: ::Windows::UI::Xaml::Controls::Button^ StartButton;
        private: ::Windows::UI::Xaml::Controls::TextBox^ Agetxt;
        private: ::Windows::UI::Xaml::Controls::TextBox^ Nametxt;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ AppName;
        private: ::Windows::UI::Xaml::VisualState^ DefaultLayout;
        private: ::Windows::UI::Xaml::VisualState^ MinimalLayout;
        private: ::Windows::UI::Xaml::VisualState^ PortraitLayout;
    };
}

