
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("7f1b51a0-7d3c-43a2-889c-c9a2e44aa40a")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("MySchoolModel", "FK_StudentGrade_Course", "Course", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Course), "StudentGrade", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(StudentGrade), True)>
<Assembly: EdmRelationshipAttribute("MySchoolModel", "FK_StudentGrade_Student", "Person", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Person), "StudentGrade", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(StudentGrade), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class MySchoolEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new MySchoolEntities object using the connection string found in the 'MySchoolEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=MySchoolEntities", "MySchoolEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new MySchoolEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "MySchoolEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new MySchoolEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "MySchoolEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Courses() As ObjectSet(Of Course)
        Get
            If (_Courses Is Nothing) Then
                _Courses = MyBase.CreateObjectSet(Of Course)("Courses")
            End If
            Return _Courses
        End Get
    End Property

    Private _Courses As ObjectSet(Of Course)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property People() As ObjectSet(Of Person)
        Get
            If (_People Is Nothing) Then
                _People = MyBase.CreateObjectSet(Of Person)("People")
            End If
            Return _People
        End Get
    End Property

    Private _People As ObjectSet(Of Person)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property StudentGrades() As ObjectSet(Of StudentGrade)
        Get
            If (_StudentGrades Is Nothing) Then
                _StudentGrades = MyBase.CreateObjectSet(Of StudentGrade)("StudentGrades")
            End If
            Return _StudentGrades
        End Get
    End Property

    Private _StudentGrades As ObjectSet(Of StudentGrade)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Courses EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCourses(ByVal course As Course)
        MyBase.AddObject("Courses", course)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the People EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToPeople(ByVal person As Person)
        MyBase.AddObject("People", person)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the StudentGrades EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToStudentGrades(ByVal studentGrade As StudentGrade)
        MyBase.AddObject("StudentGrades", studentGrade)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MySchoolModel", Name:="Course")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Course
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Course object.
    ''' </summary>
    ''' <param name="courseID">Initial value of the CourseID property.</param>
    ''' <param name="title">Initial value of the Title property.</param>
    ''' <param name="credits">Initial value of the Credits property.</param>
    ''' <param name="departmentID">Initial value of the DepartmentID property.</param>
    Public Shared Function CreateCourse(courseID As Global.System.String, title As Global.System.String, credits As Global.System.Int32, departmentID As Global.System.Int32) As Course
        Dim course as Course = New Course
        course.CourseID = courseID
        course.Title = title
        course.Credits = credits
        course.DepartmentID = departmentID
        Return course
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property CourseID() As Global.System.String
        Get
            Return _CourseID
        End Get
        Set
            If (_CourseID <> Value) Then
                OnCourseIDChanging(value)
                ReportPropertyChanging("CourseID")
                _CourseID = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("CourseID")
                OnCourseIDChanged()
            End If
        End Set
    End Property

    Private _CourseID As Global.System.String
    Private Partial Sub OnCourseIDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCourseIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Title() As Global.System.String
        Get
            Return _Title
        End Get
        Set
            OnTitleChanging(value)
            ReportPropertyChanging("Title")
            _Title = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Title")
            OnTitleChanged()
        End Set
    End Property

    Private _Title As Global.System.String
    Private Partial Sub OnTitleChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTitleChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Credits() As Global.System.Int32
        Get
            Return _Credits
        End Get
        Set
            OnCreditsChanging(value)
            ReportPropertyChanging("Credits")
            _Credits = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Credits")
            OnCreditsChanged()
        End Set
    End Property

    Private _Credits As Global.System.Int32
    Private Partial Sub OnCreditsChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnCreditsChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DepartmentID() As Global.System.Int32
        Get
            Return _DepartmentID
        End Get
        Set
            OnDepartmentIDChanging(value)
            ReportPropertyChanging("DepartmentID")
            _DepartmentID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DepartmentID")
            OnDepartmentIDChanged()
        End Set
    End Property

    Private _DepartmentID As Global.System.Int32
    Private Partial Sub OnDepartmentIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnDepartmentIDChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MySchoolModel", "FK_StudentGrade_Course", "StudentGrade")>
     Public Property StudentGrades() As EntityCollection(Of StudentGrade)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of StudentGrade)("MySchoolModel.FK_StudentGrade_Course", "StudentGrade")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of StudentGrade)("MySchoolModel.FK_StudentGrade_Course", "StudentGrade", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MySchoolModel", Name:="Person")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Person
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Person object.
    ''' </summary>
    ''' <param name="personID">Initial value of the PersonID property.</param>
    ''' <param name="lastName">Initial value of the LastName property.</param>
    ''' <param name="firstName">Initial value of the FirstName property.</param>
    Public Shared Function CreatePerson(personID As Global.System.Int32, lastName As Global.System.String, firstName As Global.System.String) As Person
        Dim person as Person = New Person
        person.PersonID = personID
        person.LastName = lastName
        person.FirstName = firstName
        Return person
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property PersonID() As Global.System.Int32
        Get
            Return _PersonID
        End Get
        Set
            If (_PersonID <> Value) Then
                OnPersonIDChanging(value)
                ReportPropertyChanging("PersonID")
                _PersonID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("PersonID")
                OnPersonIDChanged()
            End If
        End Set
    End Property

    Private _PersonID As Global.System.Int32
    Private Partial Sub OnPersonIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnPersonIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property LastName() As Global.System.String
        Get
            Return _LastName
        End Get
        Set
            OnLastNameChanging(value)
            ReportPropertyChanging("LastName")
            _LastName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("LastName")
            OnLastNameChanged()
        End Set
    End Property

    Private _LastName As Global.System.String
    Private Partial Sub OnLastNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLastNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property FirstName() As Global.System.String
        Get
            Return _FirstName
        End Get
        Set
            OnFirstNameChanging(value)
            ReportPropertyChanging("FirstName")
            _FirstName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("FirstName")
            OnFirstNameChanged()
        End Set
    End Property

    Private _FirstName As Global.System.String
    Private Partial Sub OnFirstNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFirstNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property HireDate() As Nullable(Of Global.System.DateTime)
        Get
            Return _HireDate
        End Get
        Set
            OnHireDateChanging(value)
            ReportPropertyChanging("HireDate")
            _HireDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("HireDate")
            OnHireDateChanged()
        End Set
    End Property

    Private _HireDate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnHireDateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnHireDateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property EnrollmentDate() As Nullable(Of Global.System.DateTime)
        Get
            Return _EnrollmentDate
        End Get
        Set
            OnEnrollmentDateChanging(value)
            ReportPropertyChanging("EnrollmentDate")
            _EnrollmentDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("EnrollmentDate")
            OnEnrollmentDateChanged()
        End Set
    End Property

    Private _EnrollmentDate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnEnrollmentDateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnEnrollmentDateChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MySchoolModel", "FK_StudentGrade_Student", "StudentGrade")>
     Public Property StudentGrades() As EntityCollection(Of StudentGrade)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of StudentGrade)("MySchoolModel.FK_StudentGrade_Student", "StudentGrade")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of StudentGrade)("MySchoolModel.FK_StudentGrade_Student", "StudentGrade", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MySchoolModel", Name:="StudentGrade")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class StudentGrade
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new StudentGrade object.
    ''' </summary>
    ''' <param name="enrollmentID">Initial value of the EnrollmentID property.</param>
    ''' <param name="courseID">Initial value of the CourseID property.</param>
    ''' <param name="studentID">Initial value of the StudentID property.</param>
    ''' <param name="grade">Initial value of the Grade property.</param>
    Public Shared Function CreateStudentGrade(enrollmentID As Global.System.Int32, courseID As Global.System.String, studentID As Global.System.Int32, grade As Global.System.Decimal) As StudentGrade
        Dim studentGrade as StudentGrade = New StudentGrade
        studentGrade.EnrollmentID = enrollmentID
        studentGrade.CourseID = courseID
        studentGrade.StudentID = studentID
        studentGrade.Grade = grade
        Return studentGrade
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property EnrollmentID() As Global.System.Int32
        Get
            Return _EnrollmentID
        End Get
        Set
            If (_EnrollmentID <> Value) Then
                OnEnrollmentIDChanging(value)
                ReportPropertyChanging("EnrollmentID")
                _EnrollmentID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("EnrollmentID")
                OnEnrollmentIDChanged()
            End If
        End Set
    End Property

    Private _EnrollmentID As Global.System.Int32
    Private Partial Sub OnEnrollmentIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnEnrollmentIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property CourseID() As Global.System.String
        Get
            Return _CourseID
        End Get
        Set
            OnCourseIDChanging(value)
            ReportPropertyChanging("CourseID")
            _CourseID = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("CourseID")
            OnCourseIDChanged()
        End Set
    End Property

    Private _CourseID As Global.System.String
    Private Partial Sub OnCourseIDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCourseIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property StudentID() As Global.System.Int32
        Get
            Return _StudentID
        End Get
        Set
            OnStudentIDChanging(value)
            ReportPropertyChanging("StudentID")
            _StudentID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("StudentID")
            OnStudentIDChanged()
        End Set
    End Property

    Private _StudentID As Global.System.Int32
    Private Partial Sub OnStudentIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnStudentIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Grade() As Global.System.Decimal
        Get
            Return _Grade
        End Get
        Set
            OnGradeChanging(value)
            ReportPropertyChanging("Grade")
            _Grade = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Grade")
            OnGradeChanged()
        End Set
    End Property

    Private _Grade As Global.System.Decimal
    Private Partial Sub OnGradeChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnGradeChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MySchoolModel", "FK_StudentGrade_Course", "Course")>
    Public Property Course() As Course
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Course)("MySchoolModel.FK_StudentGrade_Course", "Course").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Course)("MySchoolModel.FK_StudentGrade_Course", "Course").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property CourseReference() As EntityReference(Of Course)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Course)("MySchoolModel.FK_StudentGrade_Course", "Course")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Course)("MySchoolModel.FK_StudentGrade_Course", "Course", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MySchoolModel", "FK_StudentGrade_Student", "Person")>
    Public Property Person() As Person
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Person)("MySchoolModel.FK_StudentGrade_Student", "Person").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Person)("MySchoolModel.FK_StudentGrade_Student", "Person").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property PersonReference() As EntityReference(Of Person)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Person)("MySchoolModel.FK_StudentGrade_Student", "Person")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Person)("MySchoolModel.FK_StudentGrade_Student", "Person", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region


