//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.WCFMailService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailModel", Namespace="http://schemas.datacontract.org/2004/07/MailService.Model")]
    [System.SerializableAttribute()]
    public partial class MailModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.WCFMailService.FileAttachment[] AttachmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBodyHtmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceHostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourcePasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.WCFMailService.FileAttachment[] Attachments {
            get {
                return this.AttachmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentsField, value) != true)) {
                    this.AttachmentsField = value;
                    this.RaisePropertyChanged("Attachments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBodyHtml {
            get {
                return this.IsBodyHtmlField;
            }
            set {
                if ((this.IsBodyHtmlField.Equals(value) != true)) {
                    this.IsBodyHtmlField = value;
                    this.RaisePropertyChanged("IsBodyHtml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Port {
            get {
                return this.PortField;
            }
            set {
                if ((this.PortField.Equals(value) != true)) {
                    this.PortField = value;
                    this.RaisePropertyChanged("Port");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceAddress {
            get {
                return this.SourceAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceAddressField, value) != true)) {
                    this.SourceAddressField = value;
                    this.RaisePropertyChanged("SourceAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceHost {
            get {
                return this.SourceHostField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceHostField, value) != true)) {
                    this.SourceHostField = value;
                    this.RaisePropertyChanged("SourceHost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourcePassword {
            get {
                return this.SourcePasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.SourcePasswordField, value) != true)) {
                    this.SourcePasswordField = value;
                    this.RaisePropertyChanged("SourcePassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetAddress {
            get {
                return this.TargetAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetAddressField, value) != true)) {
                    this.TargetAddressField = value;
                    this.RaisePropertyChanged("TargetAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileAttachment", Namespace="http://schemas.datacontract.org/2004/07/MailService.Model")]
    [System.SerializableAttribute()]
    public partial class FileAttachment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FileContentByteArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.IO.FileInfo InfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FileContentByteArray {
            get {
                return this.FileContentByteArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.FileContentByteArrayField, value) != true)) {
                    this.FileContentByteArrayField = value;
                    this.RaisePropertyChanged("FileContentByteArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.IO.FileInfo Info {
            get {
                return this.InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoField, value) != true)) {
                    this.InfoField = value;
                    this.RaisePropertyChanged("Info");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://127.0.0.1:3721/", ConfigurationName="WCFMailService.MailService")]
    public interface MailService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://127.0.0.1:3721/MailService/SendMail", ReplyAction="http://127.0.0.1:3721/MailService/SendMailResponse")]
        bool SendMail(ConsoleApplication1.WCFMailService.MailModel Model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://127.0.0.1:3721/MailService/ReceiveAllMail", ReplyAction="http://127.0.0.1:3721/MailService/ReceiveAllMailResponse")]
        void ReceiveAllMail();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MailServiceChannel : ConsoleApplication1.WCFMailService.MailService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailServiceClient : System.ServiceModel.ClientBase<ConsoleApplication1.WCFMailService.MailService>, ConsoleApplication1.WCFMailService.MailService {
        
        public MailServiceClient() {
        }
        
        public MailServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MailServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SendMail(ConsoleApplication1.WCFMailService.MailModel Model) {
            return base.Channel.SendMail(Model);
        }
        
        public void ReceiveAllMail() {
            base.Channel.ReceiveAllMail();
        }
    }
}
