'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class StudentGrade
    Public Property EnrollmentID As Integer
    Public Property CourseID As String
    Public Property StudentID As Integer
    Public Property Grade As Decimal

    Public Overridable Property Course As Course
    Public Overridable Property Person As Person

End Class
