<?xml version="1.0" encoding="utf-8"?><Database Name="TestDataBase" Class="LeaveDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=TestDataBase;Integrated Security=True" SettingsObjectName="DBOperate.Properties.Settings" SettingsPropertyName="TestDataBaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Leave" Member="Leaves">
    <Type Name="Leave">
      <Column Name="LeaveID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LeaveName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LeaveDay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>