'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ModalDialogWebPartUserControl

    '''<summary>
    '''AddToolBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddToolBar As Global.System.Web.UI.UserControl

    '''<summary>
    '''AddToolBarButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddToolBarButton As Global.System.Web.UI.UserControl

    '''<summary>
    '''SitePropertiesUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SitePropertiesUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''SitePropertiesGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SitePropertiesGridView As Global.Microsoft.SharePoint.WebControls.SPGridView
End Class
