'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace WCFMailservice
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MailModel", [Namespace]:="http://schemas.datacontract.org/2004/07/MailService.Model"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MailModel
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AttachmentsField() As WCFMailservice.FileAttachment
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsBodyHtmlField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PortField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SourceAddressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SourceHostField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SourcePasswordField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TargetAddressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TextField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TitleField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Attachments() As WCFMailservice.FileAttachment()
            Get
                Return Me.AttachmentsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AttachmentsField, value) <> true) Then
                    Me.AttachmentsField = value
                    Me.RaisePropertyChanged("Attachments")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsBodyHtml() As Boolean
            Get
                Return Me.IsBodyHtmlField
            End Get
            Set
                If (Me.IsBodyHtmlField.Equals(value) <> true) Then
                    Me.IsBodyHtmlField = value
                    Me.RaisePropertyChanged("IsBodyHtml")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Port() As Integer
            Get
                Return Me.PortField
            End Get
            Set
                If (Me.PortField.Equals(value) <> true) Then
                    Me.PortField = value
                    Me.RaisePropertyChanged("Port")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SourceAddress() As String
            Get
                Return Me.SourceAddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SourceAddressField, value) <> true) Then
                    Me.SourceAddressField = value
                    Me.RaisePropertyChanged("SourceAddress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SourceHost() As String
            Get
                Return Me.SourceHostField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SourceHostField, value) <> true) Then
                    Me.SourceHostField = value
                    Me.RaisePropertyChanged("SourceHost")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SourcePassword() As String
            Get
                Return Me.SourcePasswordField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SourcePasswordField, value) <> true) Then
                    Me.SourcePasswordField = value
                    Me.RaisePropertyChanged("SourcePassword")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TargetAddress() As String
            Get
                Return Me.TargetAddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TargetAddressField, value) <> true) Then
                    Me.TargetAddressField = value
                    Me.RaisePropertyChanged("TargetAddress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Text() As String
            Get
                Return Me.TextField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TextField, value) <> true) Then
                    Me.TextField = value
                    Me.RaisePropertyChanged("Text")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Title() As String
            Get
                Return Me.TitleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TitleField, value) <> true) Then
                    Me.TitleField = value
                    Me.RaisePropertyChanged("Title")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="FileAttachment", [Namespace]:="http://schemas.datacontract.org/2004/07/MailService.Model"),  _
     System.SerializableAttribute()>  _
    Partial Public Class FileAttachment
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FileContentByteArrayField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InfoField As System.IO.FileInfo
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FileContentByteArray() As Byte()
            Get
                Return Me.FileContentByteArrayField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FileContentByteArrayField, value) <> true) Then
                    Me.FileContentByteArrayField = value
                    Me.RaisePropertyChanged("FileContentByteArray")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Info() As System.IO.FileInfo
            Get
                Return Me.InfoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InfoField, value) <> true) Then
                    Me.InfoField = value
                    Me.RaisePropertyChanged("Info")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://127.0.0.1:3721/", ConfigurationName:="WCFMailservice.MailService")>  _
    Public Interface MailService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://127.0.0.1:3721/MailService/SendMail", ReplyAction:="http://127.0.0.1:3721/MailService/SendMailResponse")>  _
        Function SendMail(ByVal Model As WCFMailservice.MailModel) As Boolean
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface MailServiceChannel
        Inherits WCFMailservice.MailService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MailServiceClient
        Inherits System.ServiceModel.ClientBase(Of WCFMailservice.MailService)
        Implements WCFMailservice.MailService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function SendMail(ByVal Model As WCFMailservice.MailModel) As Boolean Implements WCFMailservice.MailService.SendMail
            Return MyBase.Channel.SendMail(Model)
        End Function
    End Class
End Namespace
