'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Layouts.CloseModalDialogRefreshParentPage

    Partial Public Class AddSiteProperty

        '''<summary>
        '''EncodedLiteral1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EncodedLiteral1 As Global.Microsoft.SharePoint.WebControls.EncodedLiteral

        '''<summary>
        '''NameInputFormTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NameInputFormTextBox As Global.Microsoft.SharePoint.WebControls.InputFormTextBox

        '''<summary>
        '''NameErrorLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NameErrorLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ValueInputFormTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValueInputFormTextBox As Global.Microsoft.SharePoint.WebControls.InputFormTextBox

        '''<summary>
        '''OKButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents OKButton As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
