'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18010
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports VBEFDeepCloneObject.VBEFDeepCloneObject

Namespace My

    'NOTE: This file is auto-generated; do not modify it directly.  To make changes,
    ' or if you encounter build errors in this file, go to the Project Designer
    ' (go to Project Properties or double-click the My Project node in
    ' Solution Explorer), and make changes on the Application tab.
    '
    Partial Friend Class MyApplication

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()> _
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            Me.IsSingleInstance = False
            Me.EnableVisualStyles = True
            Me.SaveMySettingsOnExit = True
            Me.ShutdownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
        End Sub

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()> _
        Protected Overrides Sub OnCreateMainForm()
            InitConfig()
            Me.MainForm = Config.EmpListForm
        End Sub

        ''' <summary>
        ''' Initialize the Config class for the global object.
        ''' </summary>
        Private Shared Sub InitConfig()
            Config.EmpListForm = New EmployeeList()
            Config.EmpDetailsForm = New EmployeeDetails()
            Config.BsInfoForm = New SalesInfo()
            Config.Context = New EFCloneEntities()
            Config.Years = New String() {"2006", "2007", "2008", "2009", "2010", "2011", _
             "2012"}
        End Sub

    End Class

End Namespace
