
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("6c86d35d-1b71-4686-8e1c-1f408433d273")>

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class TestDBEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new TestDBEntities object using the connection string found in the 'TestDBEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=TestDBEntities", "TestDBEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new TestDBEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "TestDBEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new TestDBEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "TestDBEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property TestTable() As ObjectSet(Of TestTable)
        Get
            If (_TestTable Is Nothing) Then
                _TestTable = MyBase.CreateObjectSet(Of TestTable)("TestTable")
            End If
            Return _TestTable
        End Get
    End Property

    Private _TestTable As ObjectSet(Of TestTable)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the TestTable EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToTestTable(ByVal testTable As TestTable)
        MyBase.AddObject("TestTable", testTable)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="TestDBModel", Name:="TestTable")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class TestTable
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new TestTable object.
    ''' </summary>
    ''' <param name="id">Initial value of the ID property.</param>
    ''' <param name="name">Initial value of the Name property.</param>
    ''' <param name="comments">Initial value of the Comments property.</param>
    Public Shared Function CreateTestTable(id As Global.System.Int32, name As Global.System.String, comments As Global.System.String) As TestTable
        Dim testTable as TestTable = New TestTable
        testTable.ID = id
        testTable.Name = name
        testTable.Comments = comments
        Return testTable
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.Int32
        Get
            Return _ID
        End Get
        Set
            If (_ID <> Value) Then
                OnIDChanging(value)
                ReportPropertyChanging("ID")
                _ID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ID")
                OnIDChanged()
            End If
        End Set
    End Property

    Private _ID As Global.System.Int32
    Private Partial Sub OnIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Name() As Global.System.String
        Get
            Return _Name
        End Get
        Set
            OnNameChanging(value)
            ReportPropertyChanging("Name")
            _Name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Name")
            OnNameChanged()
        End Set
    End Property

    Private _Name As Global.System.String
    Private Partial Sub OnNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Comments() As Global.System.String
        Get
            Return _Comments
        End Get
        Set
            OnCommentsChanging(value)
            ReportPropertyChanging("Comments")
            _Comments = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Comments")
            OnCommentsChanged()
        End Set
    End Property

    Private _Comments As Global.System.String
    Private Partial Sub OnCommentsChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCommentsChanged()
    End Sub

    #End Region
End Class

#End Region

