'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Layouts.AddElementToHeadTag

    Partial Public Class SetMeta

        '''<summary>
        '''tbPageName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbPageName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''tbKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbKey As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''tbDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdAddMeta control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddMeta As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''tbDefaultKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbDefaultKey As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''tbDefaultDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbDefaultDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdAddDefaultMeta control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddDefaultMeta As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ltrMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrMsg As Global.System.Web.UI.WebControls.Literal
    End Class
End Namespace
