'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Layouts.VBSharePointReplicatorActivity

    Partial Public Class WorkflowAssociationForm

        '''<summary>
        '''InputFormSection1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents InputFormSection1 As Global.System.Web.UI.UserControl

        '''<summary>
        '''EncodedLiteral2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EncodedLiteral2 As Global.Microsoft.SharePoint.WebControls.EncodedLiteral

        '''<summary>
        '''pickerApprover control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pickerApprover As Global.Microsoft.SharePoint.WebControls.PeopleEditor

        '''<summary>
        '''InputFormSection3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents InputFormSection3 As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtInstructions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtInstructions As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnsSaveCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnsSaveCancel As Global.System.Web.UI.UserControl

        '''<summary>
        '''PlaceHolder1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder1 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''AssociateWorkflow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AssociateWorkflow As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''PlaceHolder2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder2 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''Cancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Cancel As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''PickerHierarchyControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PickerHierarchyControl As Global.Microsoft.SharePoint.WebControls.ScriptLink
    End Class
End Namespace
